---
agents:
  memory: "2G"

steps:
  - label: ":elasticsearch: :javascript: ES JavaScript Transport Benchmark (Linux)"
    command: ./.buildkite/benchmark.sh
    agents:
      image: "node:lts@sha256:64af3819f9275802414d7cdc38c27e9d82bd564dec4d4da87d008255d36c63b4"
