---
agents:
  memory: "2G"

steps:
  - label: ":elasticsearch: :javascript: ES JavaScript Transport Benchmark (Linux)"
    command: ./.buildkite/benchmark.sh
    agents:
      image: "node:lts@sha256:bb20cf73b3ad7212834ec48e2174cdcb5775f6550510a5336b842ae32741ce6c"
