---
agents:
  memory: "2G"

steps:
  - label: ":elasticsearch: :javascript: ES JavaScript Transport Benchmark (Linux)"
    command: ./.buildkite/benchmark.sh
    agents:
      image: "node:lts@sha256:e9891237dfbb1de60ce19e9ff9fac5d73ad9c37da303ad72ff2a425ad1057e71"
