#!/usr/bin/env node
/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

// Generates src/version.generated.ts with the transport version at build time.
// This avoids createRequire(import.meta.url) + require('../package.json') in ESM,
// which breaks bundlers (Bun, Rolldown, etc.) because they cannot resolve the path
// relative to the bundled output.

const fs = require('fs')
const path = require('path')

const rootDir = path.join(__dirname, '..')
const pkg = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf8'))

const outPath = path.join(rootDir, 'src', 'version.generated.ts')
const content = `/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by scripts/generate-version.js - do not edit manually.
 */

export const transportVersion: string = '${pkg.version}'
`

fs.writeFileSync(outPath, content, 'utf8')
console.log(`Generated ${outPath} (transport: ${pkg.version})`)
