/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

export const kSniffEnabled = Symbol('sniff enabled')
export const kNextSniff = Symbol('next sniff')
export const kIsSniffing = Symbol('is sniffing')
export const kSniffInterval = Symbol('sniff interval')
export const kSniffOnConnectionFault = Symbol('sniff on connection fault')
export const kSniffEndpoint = Symbol('sniff endpoint')
export const kRequestTimeout = Symbol('request timeout')
export const kRetryOnTimeout = Symbol('retry on timeout')
export const kCompression = Symbol('compression')
export const kMaxRetries = Symbol('max retries')
export const kName = Symbol('name')
export const kOpaqueIdPrefix = Symbol('opaque id prefix')
export const kGenerateRequestId = Symbol('generate request id')
export const kContext = Symbol('context')
export const kConnectionPool = Symbol('connection pool')
export const kSerializer = Symbol('serializer')
export const kDiagnostic = Symbol('diagnostics')
export const kHeaders = Symbol('headers')
export const kNodeFilter = Symbol('node filter')
export const kNodeSelector = Symbol('node selector')
export const kJsonOptions = Symbol('secure json parse options')
export const kStatus = Symbol('status')
export const kProductCheck = Symbol('product check')
export const kCaFingerprint = Symbol('ca fingerprint')
export const kMaxResponseSize = Symbol('max response size')
export const kMaxCompressedResponseSize = Symbol('max compressed response size')
export const kJsonContentType = Symbol('json content type')
export const kNdjsonContentType = Symbol('ndjson content type')
export const kAcceptHeader = Symbol('accept header')
export const kRedaction = Symbol('redaction')
export const kRetryBackoff = Symbol('retry backoff')
export const kOtelTracer = Symbol('opentelemetry tracer')
export const kOtelOptions = Symbol('opentelemetry options')
