name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Backport
        uses: tibdex/backport@9565281eda0731b1d20c4025c43339fb0a23812e # v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
