name: Publish package to npm
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to build and publish"
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm
      - run: npm install
      - run: npm test
      - name: npm publish
        run: |
          version=$(jq -r .version package.json)
          tag_meta=$(echo "$version" | cut -s -d '-' -f2)
          if [[ -z "$tag_meta" ]]; then
            npm publish --provenance --access public
          else
            tag=$(echo "$tag_meta" | cut -d '.' -f1)
            npm publish --provenance --access public --tag "$tag"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish version on GitHub
        run: |
          version=$(jq -r .version package.json)
          tag_meta=$(echo "$version" | cut -s -d '-' -f2)
          if [[ -z "$tag_meta" ]]; then
            gh release create \
              --target "$BRANCH_NAME" \
              --title "v$version" \
              "v$version"
          else
            tag_main=$(echo "$version" | cut -d '-' -f1)
            gh release create \
              -n "This is a $tag_main pre-release. Changes may not be stable." \
              --latest=false \
              --prerelease \
              --target "$BRANCH_NAME" \
              --title "v$version" \
              "v$version"
          fi
        env:
          BRANCH_NAME: ${{ github.event.inputs.branch }}
          GH_TOKEN: ${{ github.token }}
